version=0.1

[dev.global.parameters]
#stack-name = "Buckets-Dev"
region = "us-east-1"
parameter_overrides = "Environment=dev"

[prod.global.parameters]
#stack-name = "Buckets-Prod"
region = "us-east-1"
parameter_overrides = "Environment=prod"
