AWSTemplateFormatVersion: "2010-09-09"

Description: Sets up the DNS configuration for the domain

Parameters:
  Environment:
    Description: The environment to deploy the buckets in
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
  Domain:
    Description: The domain to deploy the site to, i.e. snowdevilsasu.com
    Type: String

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Resources:
  Zone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: The hosted zone for the Snow Devils website
#      HostedZoneTags:
#        - HostedZoneTag
      Name: !Ref Domain
#      QueryLoggingConfig:
#        QueryLoggingConfig
#      VPCs:
#        - VPC

  WebsiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
#      DomainValidationOptions:
#        - DomainName: !Ref Domain
#          HostedZoneId: !Ref Zone
      ValidationMethod: DNS


Outputs:
  NameServers:
    Description: The name servers to use in registering this domain name to correctly route to these DNS queries.
    Value: !GetAtt Zone.NameServers

  HostedZoneId:
    Description: The id of the hosted zone created
    Value: !Ref Zone

  ZoneCertificateArn:
    Description: The ARN for the certificate for the zone created
    Value: !Ref WebsiteCertificate