AWSTemplateFormatVersion: "2010-09-09"

Description: The root stack for the Snow Devils ASU Website and all of its resources and architecture

Parameters:
  Environment:
    Description: The environment to deploy the buckets in
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
  HostedZoneId:
    Description: The id of the hosted zone of the domain to deploy the site to.
    Type: String
  HostedZoneDomain:
    Description: The root domain to deploy this site to. *This must be* the same as the name of the Hosted Zone given by the HostedZoneId.
    Type: String
  Subdomain:
    Description: The subdomain of the hosted zone to deploy this site to. A new record set will be created in the hosted zone for this subdomain to point to the CDN created.
    Type: String

Conditions:
  IsApex: !Equals [!Ref Subdomain, ""]

Resources:
  Buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./WebsiteBucket.yaml
      Parameters:
        Domain: !If [IsApex, !Ref HostedZoneDomain, !Join [".", [!Ref Subdomain, !Ref HostedZoneDomain]]]
      TimeoutInMinutes: 5

  WebsiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If [IsApex, !Ref HostedZoneDomain, !Join [".", [!Ref Subdomain, !Ref HostedZoneDomain]]]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !If [IsApex, !Ref HostedZoneDomain, !Join [".", [!Ref Subdomain, !Ref HostedZoneDomain]]] #!Ref RootDomain
          HostedZoneId: !Ref HostedZoneId

  # Sets up the CDN and its DNS routes
  CDN:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./CloudFrontDistribution.yaml
      TimeoutInMinutes: 10
      Parameters:
        Environment: !Ref Environment
        DomainName: !If [IsApex, !Ref HostedZoneDomain, !Join [".", [!Ref Subdomain, !Ref HostedZoneDomain]]]
        DomainCertificateArn: !Ref WebsiteCertificate # !GetAtt Domain.Outputs.ZoneCertificateArn
        HostedZoneId: !Ref HostedZoneId
        S3Bucket: !GetAtt Buckets.Outputs.S3Bucket
        S3BucketName: !GetAtt Buckets.Outputs.S3BucketDomainName
        S3BucketRootArn: !GetAtt Buckets.Outputs.S3BucketArn
#        S3LoggingBucketDomain: !GetAtt Buckets.Outputs.S3LoggingBucketDomainName


Outputs:
  CloudFrontDistribution:
    Description: CloudFront Distribution
    Value: !GetAtt CDN.Outputs.CloudFrontDistribution

  S3WebsiteBucket:
    Description: The name of the bucket where the website content should be stored. Upload the website assets to this bucket.
    Value: !GetAtt Buckets.Outputs.S3Bucket

  DeploymentDomain:
    Description: The domain this website was deployed to. Same as the input given in.
    Value: !Join [".", [!Ref Subdomain, !Ref HostedZoneDomain]]
