AWSTemplateFormatVersion: "2010-09-09"

Description: The root stack for the Snow Devils ASU Website and all of its resources and architecture

Parameters:
  Environment:
    Description: The environment to deploy the buckets in
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

Resources:
  Buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./WebsiteBucket.yaml
      Parameters:
        Environment: !Ref Environment
      TimeoutInMinutes: 5

  CDN:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./CloudFrontDistribution.yaml
      TimeoutInMinutes: 10
      Parameters:
        Environment: !Ref Environment
        DomainName: ""
        S3Bucket: !GetAtt Buckets.Outputs.S3Bucket
        S3BucketName: !GetAtt Buckets.Outputs.S3BucketDomainName
        S3BucketRootArn: !GetAtt Buckets.Outputs.S3BucketArn
        S3LoggingBucketDomain: !GetAtt Buckets.Outputs.S3LoggingBucketDomainName


Outputs:
  CloudFrontDistribution:
    Description: CloudFront Distribution
    Value: !GetAtt CDN.Outputs.CloudFrontDistribution

  S3BucketDualStackDomainName:
    Description: The dual stack (IPv6) domain name for the S3 Bucket
    Value: !GetAtt Buckets.Outputs.S3BucketDualStackDomainName
