version=0.1

[dev.global.parameters]
region = "us-east-1"
parameter_overrides = "Environment=dev RootDomain=snowdevilsasu.com"
stack_name = "Website-Dev"

[prod.global.parameters]
region = "us-east-1"
parameter_overrides = "Environment=prod RootDomain=snowdevilsasu.com"
stack_name = "Website-Prod"

[aarondev.global.parameters]
region = "us-east-1"
parameter_overrides = "Environment=prod HostedZoneId=Z0342598BXSFEDBIORG1 HostedZoneDomain=snowdevils.link Subdomain=beta"
stack_name = "Website-Dev"