AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFormation template for S3 bucket to host static website

Parameters:
  Domain:
    Description: The domain the buckets are storing content for
    Type: String

Resources:
  # TODO: Do i really need a logging bucket?
#  LoggingBucket:
#    Type: 'AWS::S3::Bucket'
#    Properties:
#      AccessControl: LogDeliveryWrite
#      BucketName: !Join ["-", [!Ref Domain, !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]], "logs"]] # Essentially appends a random id to the end of the domain (part of stack id)
#      LifecycleConfiguration:
#        Rules:
#          - ExpirationInDays: 1
#            Id: DeleteOldLogs
##            Prefix: String
#            Status: Enabled

  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join ["-", [!Ref Domain, !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
#      LoggingConfiguration:
#        DestinationBucketName: !Ref LoggingBucket
#        LogFilePrefix: !Join ['', ['bucket-', !Ref Environment, '/']]
      OwnershipControls: 
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # Tags: 
      #   - Tag

Outputs:
  S3Bucket:
    Description: The name of the created S3 Website Bucket
    Value: !Ref WebsiteBucket

  S3BucketDomainName:
    Description: The domain name of the created S3 bucket
    Value: !GetAtt WebsiteBucket.DomainName

  S3BucketDualStackDomainName:
    Description: The dual stack (IPv6) domain name for the S3 Bucket
    Value: !GetAtt WebsiteBucket.DualStackDomainName

  S3BucketArn:
    Description: The ARN of the S3 Website bucket
    Value: !GetAtt WebsiteBucket.Arn

#  S3LoggingBucket:
#    Value: !Ref LoggingBucket
#    Description: The S3 logging bucket name
#
#  S3LoggingBucketDomainName:
#    Value: !GetAtt LoggingBucket.DomainName
#
#  S3LoggingBucketDualStackDomainName:
#    Value: !GetAtt LoggingBucket.DualStackDomainName
